name: AutoPickup
version: {{version}}
api-version: 1.13
main: com.philderbeast.autopickup.AutoPickupPlugin
softdepend: [MythicDrops, MythicMobs, QuickSell, FortuneBlocks, AutoSell, StackableItems, PrisonGems, MyPet, TokenEnchant]
commands:
  autopickup:
    aliases: [ap]
    description: Displays AutoPickup Help
    usage: /ap help
  autosmelt:
    aliases: [as]
    description: Displays AutoPickup Help
    usage: /as help
  autoblock:
    aliases: [ab]
    description: Displays AutoPickup Help
    usage: /ab help
  autosell:
    description: Enables autoselling with QuickSell
    usage: /autosell help
  fullnotify:
    aliases: [fn]
    description: Enables inventory full notifications
    usage: /fullnotify help